Guinea_pig = "----CTGG---GGCAACGGCGTGTCCTCGCTAACCCAGACG---AACGTGATGGAAA-GGCTACGCCGATTACCGGGAAGA-ACCTGCTGAGACTGAATGTCCCCCACAACCTAGGAGCCGTGAGGCCCGAGGTATCATATGCTCCGGCTAGGCGCTCGGACTGATGGTTCGCCTTCCCGAACAAGGCCCGTCCACGTATCCCCCACAGCCGCCAGGCCCCGTGAGAT-----ACTCCCACTATCCGTCTATGTAC----------GGTCTCCAA---GGGTGCCTTTTTTAGGTGACGGCTAACTACGCCGCCCAGACTGCCAGACCGCTTCGCAAGCAAGCGCCGGCGGCAGTAAAACATGCACAAGG"
Cat = "TCGACTGGCTTAACGAGGGCGAG----AGTTGA-GCGGCTGCACAATGGCACAGGCGCAGT---ATTTATTACTGTAGGGGCATCCGTCG----CCGGCTCTTGTCAATCTGCGCCTTTGATGAGGCCCGAGGTATCATATGCTCCGGCTAGGCGCTCGGACTGATGGTTCGCCTTCCCGAACAAGGCCCGTCCACGTATCCCCCACAGCCGCCAGGCCCCGTGAGAT-----ACTCCCACTATCCGTCTATGTAC----------GGTCTCCAA---GGGTGCCTTTTTTAGGTGACGGCTAACTACGCCGCCCAGACTGCCAGACCGCTTCGCAAGCAAGCGCCGGCGGCAGTAAAACATGCACAAGG"
reference = "CTAACTGGACGGCCGAGGGCGAG----AGTTGA-GCGGCTG---AGTGGGACGGAGACCGTGCCATCGGGTACTGAAAAGGCATCCGTCG----CCGGCGTCCCCTGATCTGCGGGAGCCGCGAGGCCCGATGGATCACATGCTTCGGCTAAGCGCTCGGACTGATGGTTCGCCTTCCCGAACAAGGCCCGTCCACGTATCCCCCACAGCCGCCAGGCCCCGTGAGAT-----ACTCCCACTATCCGTCTATGTAC----------GGTCTCCAA---GGGCGCCCCCCCTAGGTGACGGCTAACTGCACCGCCCAGACCGCCAGACCGCTTCGCAAGCAAGCGTCGGCGGCAGTAAAACGTGAACAAGG"
Patient_1 = "CTAACTGGACGGCCGAGGGCGAG----AGTTGA-GCGGCTG---AGTGGGACGGAGACCGTGCCATCGGGTACTGAAAAGGCATCCGTCG----CCGGCGTCCCCTGATCTGCGGGAGCCGCGAGGCCCGATGGATCACATGCTTCGGCTAAGCGCTCGGACTGATGGTTCGCCTTCCCGAACAAGGCCCGTCCACGTATCCCCCACAGCCGCCAGGCCCCGTGAGAT-----ACTCCCACTATCCGTCTATGTAC----------GGTCTCCAA---GGGCGCCCCCCCTAGGTGACGGCTAACTGCACCGCCCAGACCGCCAGACCGCTTCGCAAGCAAGCGTCGGCGGCAGTAAAACGTGAACAAGG"
Patient_8 = "CTAACTGGACGGCCGAGGGCGAG----AGTTGA-GCGGCTG---AGTGGGACGGAGACCGTGCCATCGGGTACTGAAAAGGCATCCGTCG----CCGGCGTCCCCTGATCTGCGGGAGCCGCGAGGCCCGATGGATCACATGCTTCGGCTAAGCGCTCGGACTGATGGTTCGCCTTCCCGAACAAGGCCCGTCCACGTATCCCCCACAGCCGCCAGGCCCCGTGAGAT-----ACTCCCACTATCCGTCTATGTAC----------GGTCTCCAA---GGGCGCCCCCCCTAGGTGACGGCTAACTGCACCGCCCAGACCGCCAGACCGCTTCGCAAGCAAGCGTCGGCGGCAGTAAAACATGAACAAGG"
Patient_7 = "TTAACTGGACGGCCGAGGGCGAG----AGTTGA-GCGGCTG---AGTGGGACGGAGACCGTGCCATCGGGTACTGAAAAGGCATCCGTCG----CCGGCGTCCCCTGATCTGCGGGAGCCGTGAGGCCCGAGGGATCATATGCTCCGGCTAGGCGCTCGGACTGATGGTTCGCCTTCCCGAACAAGGCCCGTCCACGTATCCCCCACAGCCGCCAGGCCCCGTGAGAT-----ACTCCCACTATCCGTCTATGTAC----------GGTCTCCAA---GGGTGCCTTTTTTAGGTGACGGCTAACTACGCCGCCCAGACTGCCAGACCGCTTCGCAAGCAAGCGTCGGCGGCAGTAAAACATGAACAAGG"
Patient_10 = "CTAACTGGACGGCCGAGGGCGAG----AGTTGA-GCGGCTG---AGTGGGACGGAGACCGTGCCATCGGGTACTGAAAAGGCATCCGTCG----CCGGCGTCCCCTGATCTGCGGGAGCCGTGAGGCCCGAGGTATCATATGCTCCGGCTAGGCGCTCGGACTGATGGTTCGCCTTCCCGAACAAGGCCCGTCCACGTATCCCCCACAGCCGCCAGGCCCCGTGAGAT-----ACTCCCACTATCCGTCTATGTAC----------GGTCTCCAA---GGGTGCCTTCTTTAGGTGACGGCTAACTACGCCGCCCAGACTGCCAGACCGCTTCGCAAGCAAGCGCCGGCGGCAGTAAAACATGCACAAGG"
Patient_14 = "TTAACTGGACGGCCGAGGGCGAG----AGTTGA-GCGGCTG---AGTGGGACGGAGACCGTGCCATCGGGTACTGAAAAGGCATCCGTCG----CCGGCGTCCCCTGATCTGCGGGAGCCGTGAGGCCCGAGGTATCATATGCTCCGGCTAGGCGCTCGGACTGATGGTTCGCCTTCCCGAACAAGGCCCGTCCACGTATCCCCCACAGCCGCCAGGCCCCGTGAGAT-----ACTCCCACTATCCGTCTATGTAC----------GGTCTCCAA---GGGTGCCTTCTTTAGGTGACGGCTAACTACGCCGCCCAGACTGCCAGACCGCTTCGCAAGCAAGCGCCGGCGGCAGTAAAACATGCACAAGG"
Patient_5 = "TTAACTGGACGGCCGAGGGCGAG----AGTTGA-GCGGCTG---AGTGGGACGGAGACCGTGCCATCGGGTACTGAAAAGGCATCCGTCG----CCGGCGTCCCCTGATCTGCGGGAGCCGTGAGGCCCGAGGTATCATATGCTCCGGCTAGGCGCTCGGACTGATGGTTCGCCTTCCCGAACAAGGCCCGTCCACGTATCCCCCACAGCCGCCAGGCCCCGTGAGAT-----ACTCCCACTATCCGTCTATGTAC----------GGTCTCCAA---GGGTGCCTTCTTTAGGTGACGGCTAACTACGCCGCCCAGACTGCCAGACCGCTTCGCAAGCAAGCGCCGGCGGCAGTAAAACATGCACAAGG"
Patient_9 = "TTAACTGGACGGCCGAGGGCGAG----AGTTGA-GCGGCTG---AGTGGGACGGAGACCGTGCCATCGGGTACTGAAAAGGCATCCGTCG----CCGGCGTCCCCTGATCTGCGGGAGCCGTGAGGCCCGAGGTATCATATGCTCCGGCTAGGCGCTCGGACTGATGGTTCGCCTTCCCGAACAAGGCCCGTCCACGTATCCCCCACAGCCGCCAGGCCCCGTGAGAT-----ACTCCCACTATCCGTCTATGTAC----------GGTCTCCAA---GGGTGCCTTCTTTAGGTGACGGCTAACTACGCCGCCCAGACTGCCAGACCGCTTCGCAAGCAAGCGCCGGCGGCAGTAAAACATGCACAAGG"
Bat = "TTAACTGGACGGCCGAGGGCGAG----AGTTGA-GCGGCTG---AGTGGGACGGAGACCGTGCCATCGGGTACTGAAAAGGCATCCGTCG----CCGGCGTCCCCTGATCTGCGGGAGCCGTGAGGCCCGAGGTATCATATGCTCCGGCTAGGCGCTCGGACTGATGGTTCGCCTTCCCGAACAAGGCCCGTCCACGTATCCCCCACAGCCGCCAGGCCCCGTGAGAT-----ACTCCCACTATCCGTCTATGTAC----------GGTCTCCAA---GGGTGCCTTTTTTAGGTGACGGCTAATTACGCCGCCCAGACTGCCAGACCGCTTCGCAAGCAAGCGCCGGCGGCAGTAAAACATGCACAAGG"
Patient_12 = "TTAACTGGACGGCCGAGGGCGAG----AGTTGA-GCGGCTG---AGTGGGACGGAGACCGTGCCATCGGGTACTGAAAAGGCATCCGTCG----CCGGCGTCCCCTGATCTGCGGGAGCCGTGAGGCCCGAGGTATCATATGCTCCGGCTAGGCGCTCGGACTGATGGTTCGCCTTCCCGAACAAGGCCCGTCCACGTATCCCCCACAGCCGCCAGGCCCCGTGAGAT-----ACTCCCACTATCCGTCTATGTAC----------GGTCTCCAA---GGGTGCCTTTTTTAGGTGACGGCTAACTACGCCGCCCAGACTGCCAGACCGCTTCGTAAGCAAGCGCCGGCGGCAGTAAAACATGCACAAGG"
Patient_2 = "TTAACTGGACGGCCGAGGGCGAG----AGTTGA-GCGGCTG---AGTGGGACGGAGACCGTGCCATCGGGTACTGAAAAGGCATCCGTCG----CCGGCGTCCCCTGATCTGCGGGAGCCGTGAGGCCCGAGGTATCATATGCTCCGGCTAGGCGCTCGGACTGATGGTTCGCCTTCCCGAACAAGGCCCGTCCACGTATCCCCCACAGCCGCCAGGCCCCGTGAGAT-----ACTCCCACTATCCGTCTATGTAC----------GGTCTCCAA---GGGTGCCTTTTTTAGGCGACGGCTAACTACGCCGCCCAGACTGCCAGACCGCTTCGCAAGCAAGCGCCGGCGGCAGTAAAACATGCACAAGG"
Patient_4 = "TTAACTGGACGGCCGAGGGCGAG----AGTTGA-GCGGCTG---AGTGGGACGGAGACCGTGCCATCGGGTACTGAAAAGGCATCCGTCG----CCGGCGTCCCCTGATCTGCGGGAGCCGTGAGGCCCGAGGTATCATATGCTCCGGCTAGGCGCTCGGACTGATGGTTCGCCTTCCCGAACAAGGCCCGTCCACGTATCCCCCACAGCCGCCAGGCCCCGTGAGAT-----ACTCCCACTATCCGTCTATGTAC----------GGTCTCCAA---GGGTGCCTTTTTTAGGTGACGGCTAACTACGCCGCCCAGTCTGCCAGACCGCTTCGCAAGCAAGCGCCGGCGGCAGTAAAACATGCACAAGG"
Patient_6 = "TTAACTGGACGGCCGAGGGCGAG----AGTTGA-GCGGCTG---AGTGGGACGGAGACCGTGCCATCGGGTACTGAAAAGGCATCCGTCG----CCGGCGTCCCCTGATCTGCGGGAGCCGTGAGGCCCGAGGTATCATATGCTCCGGCTAGGCGCTCGGACTGATGGTTCGCCTTCCCGAACAAGGCCCGTCCACGTATCCCCCACAGCCGCCAGGCCCCGTGAGAT-----ACTCCCACTATCCGTCTATGTAC----------GGTCTCCAA---GGGTGCCTTTTTTAGGTGACGGCTAACTACGCCGCCCAGACTGCCAGACCGCTTCGCAATCAAGCGCCGGCGGCAGTAAAACATGCACAAGG"
Patient_11 = "TTAACTGGACGGCCGAGGGCGAG----AGTTGA-GCGGCTG---AGTGGGACGGAGACCGTGCCATCGGGTACTGAAAAGGCATCCGTCG----CCGGCGTCCCCTGATCTGCGGGAGCCGTGAGGCCCGAGGTATCATATGCTCCGGCTAGGCGCTCGGACTGATGGTTCGCCTTCCCGAACAAGGCCCGTCCACGTATCCCCCACAGCCGCCAGGCCCCGTGAGAT-----ACTCCCACTATCCGTCTATGTAC----------GGTCTCCAA---GGGTGCCTTTTTTAGGTGACGGCTAACTACGCCGCCCAGACTGCCAGACCGCTTCGCAAGCAAGCGCCGGCGGCAGTAAAACATGCACAAGG"
Patient_13 = "TTAACTGGACGGCCGAGGGCGAG----AGTTGA-GCGGCTG---AGTGGGACGGAGACCGTGCCATCGGGTACTGAAAAGGCATCCGTCG----CCGGCGTCCCCTGATCTGCGGGAGCCGTGAGGCCCGAGGTATCATATGCTCCGGCTAGGCGCTCGGACTGATGGTTCGCCTTCCCGAACAAGGCCCGTCCACGTATCCCCCACAGCCGCCAGGCCCCGTGAGAT-----ACTCCCACTATCCGTCTATGTAC----------GGTCTCCAA---GGGTGCCTTTTTTAGGTGACGGCTAACTACGCCGCCCAGACTGCCAGACCGCTTCGCAAGCAAGCGCCGGCGGCAGTAAAACATGCACAAGG"
Patient_15 = "TTAACTGGACGGCCGAGGGCGAG----AGTTGA-GCGGCTG---AGTGGGACGGAGACCGTGCCATCGGGTACTGAAAAGGCATCCGTCG----CCGGCGTCCCCTGATCTGCGGGAGCCGTGAGGCCCGAGGTATCATATGCTCCGGCTAGGCGCTCGGACTGATGGTTCGCCTTCCCGAACAAGGCCCGTCCACGTATCCCCCACAGCCGCCAGGCCCCGTGAGAT-----ACTCCCACTATCCGTCTATGTAC----------GGTCTCCAA---GGGTGCCTTTTTTAGGTGACGGCTAACTACGCCGCCCAGACTGCCAGACCGCTTCGCAAGCAAGCGCCGGCGGCAGTAAAACATGCACAAGG"
Patient_16 = "TTAACTGGACGGCCGAGGGCGAG----AGTTGA-GCGGCTG---AGTGGGACGGAGACCGTGCCATCGGGTACTGAAAAGGCATCCGTCG----CCGGCGTCCCCTGATCTGCGGGAGCCGTGAGGCCCGAGGTATCATATGCTCCGGCTAGGCGCTCGGACTGATGGTTCGCCTTCCCGAACAAGGCCCGTCCACGTATCCCCCACAGCCGCCAGGCCCCGTGAGAT-----ACTCCCACTATCCGTCTATGTAC----------GGTCTCCAA---GGGTGCCTTTTTTAGGTGACGGCTAACTACGCCGCCCAGACTGCCAGACCGCTTCGCAAGCAAGCGCCGGCGGCAGTAAAACATGCACAAGG"
Patient_3 = "TTAACTGGACGGCCGAGGGCGAG----AGTTGA-GCGGCTG---AGTGGGACGGAGACCGTGCCATCGGGTACTGAAAAGGCATCCGTCG----CCGGCGTCCCCTGATCTGCGGGAGCCGTGAGGCCCGAGGTATCATATGCTCCGGCTAGGCGCTCGGACTGATGGTTCGCCTTCCCGAACAAGGCCCGTCCACGTATCCCCCACAGCCGCCAGGCCCCGTGAGAT-----ACTCCCACTATCCGTCTATGTAC----------GGTCTCCAA---GGGTGCCTTTTTTAGGTGACGGCTAACTACGCCGCCCAGACTGCCAGACCGCTTCGCAAGCAAGCGCCGGCGGCAGTAAAACATGCACAAGG"
Rabid_raccoon_3 = "CTAACTGGACGGCCGAGGGCGAG----AGTTGA-GCGGCTG---AGTGGGACGGAGACCGTGCCATCGGGTACTGAAAAGGCATCCGTCG----CCGGCGTCCCCTGATCTGCGGGAGCCGCGGGGTTCGGTAGGCCGCACGTCCCGATCGATTTCACGAATCGGCGGGC---------------GACCCACTTATGTGCACTATTAATTTACTA---TTAGTGATATTAATGAATTTTTCTGAGCGTCAGTGTCCGAAAGGAGCTGGGCTCAGATCGAAGCGTCCCCCTCAGATGCATAATGACCGCGTCTTCGTGACCACTGGATTGTCTTTCGGGCGTGTACCAATGACGACACGCTGCACGCAGGA"
Rabid_raccoon_1 = "CTAACTGGACGGCCGAGGGCGAG----AGTTGA-GCGGCTG---AGTGGGACGGAGACCGTGCCATCGGGTACTGAAAAGGCATCCGTCG----CCGGCGTCCCCTGATCTGCGGGAGCCGCTGGATTTTGTAGGCTGCACACCCTAGTCGATCGCACGAATCGGCGTGTCGTTCTTTCGAACAAGGCCCGTCCACGTATCCCCCACAGCCGCCAGGCCCCGTGAGAT-----ACTCCCACTATCCGTCTATGTAC----------GGTCTCCAA---AGGCGTCCCCCTCAGATACAGGCTGCCCGCGTCTTCCAAATCACCGGATTCTCTTTCGGGCGTATACCAGTGACGACACGCTGCACGCAGGA"
Rabid_raccoon_2 = "CTAACTGGACGGCCGAGGGCGAG----AGTTGA-GCGGCTG---AGTGGGACGGAGACCGTGCCATCGGGTACTGAAAAGGCATCCGTCG----CCGGCGTCCCCTGATCTGCGGGAGCCGCGGAGTCCGGTAGGCCGCGCGCCCCGGTTGATCGTATAGTTCGGCTGGCGACCCTCTCGAACAAGGCCCGTCCACGTATCCCCCACAGCCGCCAGGCCCCGTGAGAT-----ACTCCCACTATCCGTCTATGTAC----------GGTCTCCAA---GGACATACCCCTCGCATGACGGCGGACCGTGTTTTTCAGACCATCGAGTTGCCCTGCGGGTGTGTACAAGTAATGACGCGCCGCACGTGGAA"
Rabid_raccoon_4 = "CTAACTGGACGGCCGAGGGCGAG----AGTTGA-GCGGCTG---AGTGGGACGGAGACCGTGCCATCGGGTACTGAAAAGGCATCCGTCG----CCGGCGTCCCCTGATCTGCGGGAGCCGCGGAGTCCGGTAGGCCGCGCGCCCCGGTTGATCGTATAGTTCAGCTGGTCGCCCTCTCGAACAAGGCCCGTCCACGTATCCCCCACAGCCGCCAGGCCCCGTGAGAT-----ACTCCCACTATCCGTCTATGTAC----------GGTCTCCAA---GGACATACCCCTCGCATGACGGCGGACCGTGTTTTTCAGACCATCGAGTTGCCCTGCGGGTGTGTACAAGTAATGACGCGCCGCAAGTGGAA"

names = [
"Guinea_pig", 
"Cat", 
"Patient_7", 
"reference", 
"Patient_1", 
"Patient_9", 
"Patient_8", 
"Patient_6", 
"Patient_10", 
"Patient_16", 
"Patient_11", 
"Patient_2", 
"Patient_5", 
"Patient_15", 
"Patient_12", 
"Patient_3", 
"Patient_4", 
"Patient_14", 
"Bat", 
"Patient_13", 
"Rabid_raccoon_3", 
"Rabid_raccoon_1", 
"Rabid_raccoon_2", 
"Rabid_raccoon_4" ]

samples = [
Guinea_pig, 
Cat, 
Patient_7, 
reference, 
Patient_1, 
Patient_9, 
Patient_8, 
Patient_6, 
Patient_10, 
Patient_16, 
Patient_11, 
Patient_2, 
Patient_5, 
Patient_15, 
Patient_12, 
Patient_3, 
Patient_4, 
Patient_14, 
Bat, 
Patient_13, 
Rabid_raccoon_3, 
Rabid_raccoon_1, 
Rabid_raccoon_2, 
Rabid_raccoon_4 ]

def diff(seq_a, seq_b) :
	count = 0
	for pos in range(len(seq_a)):
		if (seq_a[pos] != seq_b[pos]):
			count +=1
	return count

for i1 in range(len(samples)):
	print("-----------------------------------------")
	for i2 in range(len(samples)):
		if (i1 != i2):
			print(names[i1] + " + " + names[i2] + " : " + str(diff(samples[i1], samples[i2])) + "\nTransmission Events = " + str(diff(samples[i1], samples[i2]) / 4))
